# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1195, 827)
        MainWindow.setStyleSheet("QWidget {\n"
                                 "    color: white;\n"
                                 "    background-color: #121212;\n"
                                 "    font-family: Rubik;\n"
                                 "    font-size: 16pt;\n"
                                 "    font-weight: 600;\n"
                                 "}\n"
                                 "QPushButton:pressed {\n"
                                 "  background-color: #888;\n"
                                 "}\n"
                                 "QPushButton {\n"
                                 "    background-color: green;\n"
                                 "    border: none;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setEnabled(False)
        self.search_btn.setGeometry(QtCore.QRect(0, 420, 1201, 111))
        self.search_btn.setCheckable(False)
        self.search_btn.setChecked(False)
        self.search_btn.setObjectName("search_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 1191, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(0, 580, 1201, 111))
        self.play_btn.setEnabled(False)
        self.play_btn.setCheckable(False)
        self.play_btn.setChecked(False)
        self.play_btn.setObjectName("play_btn")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(950, 170, 241, 61))
        self.save_btn.setObjectName("save_btn")
        self.save_btn.setEnabled(True)
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(0, 170, 931, 61))
        self.name_line.setMaxLength(20)
        self.name_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_line.setObjectName("name_line")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(10, 120, 281, 31))
        self.name_label.setObjectName("name_label")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(10, 320, 1181, 51))
        self.status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status.setObjectName("status")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gallows"))
        self.search_btn.setText(_translate("MainWindow", "НАЙТИ ИГРОКА"))
        self.label.setText(_translate("MainWindow", "ВИСЕЛИЦА"))
        self.play_btn.setText(_translate("MainWindow", "НАЧАТЬ ИГРУ"))
        self.save_btn.setText(_translate("MainWindow", "СОХРАНИТЬ"))
        self.name_label.setText(_translate("MainWindow", "ВВЕДИТЕ ИМЯ:"))
        self.status.setText(_translate("MainWindow", "ДЛЯ ПРОДОЛЖЕНИЯ ЗАПОЛНИТЕ ИМЯ"))
