# Form implementation generated from reading ui file 'design_mode_selection.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class SelectionWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 722)
        MainWindow.setStyleSheet("QWidget {\n"
                                 "    color: #4169E1;\n"
                                 "    background-color: #ADD8E6;\n"
                                 "    font-family: Rubik;\n"
                                 "    font-size: 16pt;\n"
                                 "    font-weight: 600;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "    background-color: #1E90FF;\n"
                                 "    border: none;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #00BFFF;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color:#0000FF;\n"
                                 "}\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(80, 20, 861, 51))
        self.status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status.setObjectName("status")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(-10, 360, 1051, 111))
        self.play_btn.setCheckable(False)
        self.play_btn.setChecked(False)
        self.play_btn.setObjectName("play_btn")
        self.play_btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn_3.setGeometry(QtCore.QRect(0, 530, 1031, 111))
        self.play_btn_3.setCheckable(False)
        self.play_btn_3.setChecked(False)
        self.play_btn_3.setObjectName("play_btn_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(140, 130, 751, 71))
        self.lineEdit.setObjectName("lineEdit_2")
        self.play_btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn_4.setGeometry(QtCore.QRect(140, 220, 751, 101))
        self.play_btn_4.setCheckable(False)
        self.play_btn_4.setChecked(False)
        self.play_btn_4.setObjectName("play_btn_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gallows"))
        self.status.setText(_translate("MainWindow", "Mode selection"))
        self.play_btn.setText(_translate("MainWindow", "Learn the word"))
        self.play_btn_3.setText(_translate("MainWindow", "Guess a word"))
        self.play_btn_4.setText(_translate("MainWindow", "Play"))
