# Form implementation generated from reading ui file 'design_start.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class DesignStartWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 720)
        MainWindow.setStyleSheet("QWidget {\n"
                                 "    color: #4169E1;\n"
                                 "    background-color: #ADD8E6;\n"
                                 "    font-family: Rubik;\n"
                                 "    font-size: 16pt;\n"
                                 "    font-weight: 600;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton {\n"
                                 "    background-color: #1E90FF;\n"
                                 "    border: none;\n"
                                 "}\n"
                                 "QPushButton:hover {\n"
                                 "    background-color: #00BFFF;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    background-color:#0000FF;\n"
                                 "}\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setEnabled(True)
        self.search_btn.setGeometry(QtCore.QRect(240, 440, 551, 111))
        self.search_btn.setCheckable(False)
        self.search_btn.setChecked(False)
        self.search_btn.setObjectName("search_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 10, 1031, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setGeometry(QtCore.QRect(240, 270, 551, 61))
        self.save_btn.setObjectName("save_btn")
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(240, 160, 551, 61))
        self.name_line.setText("")
        self.name_line.setMaxLength(20)
        self.name_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_line.setObjectName("name_line")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(400, 90, 231, 61))
        self.name_label.setObjectName("name_label")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(0, 360, 1031, 51))
        self.status.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status.setObjectName("status")
        self.name_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.name_label_2.setGeometry(QtCore.QRect(20, 160, 181, 61))
        self.name_label_2.setObjectName("name_label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gallows"))
        self.search_btn.setText(_translate("MainWindow", "Find player"))
        self.label.setText(_translate("MainWindow", "Greetings !!!"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.name_label.setText(_translate("MainWindow", "Enter nickname:"))
        self.status.setText(_translate("MainWindow", "Fill in the \'nickname\' field to continue"))
        self.name_label_2.setText(_translate("MainWindow", " Nickname:"))
